title:
author: Daniel Fan
email: dfanology@protonmail.com
description: >
  My webpage in the age of mechanical reproduction.
  
show_excerpts: true

minima:
  date_format: "%d %b %Y"
  instagram: dfanology
  linkedin: daniel-fan-2a925914

header_pages:
  - about.md
  - scitech.md
  - stories.md

theme: minima
markdown: kramdown
